import React from "react";
import {
  PageContainer,
  ContentContainer1,
  ContentContainer2,
  Title,
  SubContainer,
  Box,
  TextBody,
  Video2,
  Subtitle
} from "./page_styles/about_style.js";
import Footer from "../components/footer/footer.js";
import info_video from "../imgs/info_video.mp4";

function About() {
  return (
    <>
      <PageContainer>
        <section>
          <div class="air air1"></div>
          <div class="air air2"></div>
          <div class="air air3"></div>
          <div class="air air4"></div>
        </section>
        <ContentContainer1>
          <Title>Building Tomorrow's Maritime Frontier</Title>
        </ContentContainer1>
        <ContentContainer2>
          <SubContainer>
            <Box>Vision</Box>
            <TextBody>
              We’re focused on scaling access to mission-critical maritime data.
              As a team of watch officers, veterans, and software engineers, our
              experience illuminated the challenges of the maritime environment
              and the need to operate with data-driven insights - at the ship
              and watch floor level.
            </TextBody>
          </SubContainer>
          <SubContainer>
            <Box>Approach</Box>
            <TextBody>
              <p>
                Today’s enterprise software overlooks vast amounts of data
                generated by ships across the sea. Watch officers, with
                significant responsibility in their hands, are left to make
                high-stakes judgment calls without software that serves them the
                most relevant information.
              </p>
              <p>
                Marview is building an answer: our platform fuses open-source
                data and interfaces with existing sensors throughout the
                maritime network, offering key, actionable insights on a single
                screen.
              </p>
              <p>
                We’re committed to the opportunities presented by an explosion
                in satellite bandwidth, open-source data streams, and maritime
                sensor capabilities. The maritime domain is too important, and
                too challenging, to rely on analog methods any longer.
              </p>
            </TextBody>
          </SubContainer>
        </ContentContainer2>
        <ContentContainer1>
          <SubContainer>
            <Subtitle>Charting New Opportunities</Subtitle>
            <SubContainer>
              <TextBody>
                <p>
                  We’re focused on building solutions that get actionable
                  insights into the hands of those who need it. By leveraging
                  open-source data, existing sensor capabilities, and our own
                  domain experience, we build mission-essential applications
                  unmatched by traditional enterprise software providers.
                </p>
              </TextBody>
              <Video2 src={info_video} autoPlay loop muted playsinline />
            </SubContainer>
          </SubContainer>
        </ContentContainer1>
      </PageContainer>
      <Footer />
    </>
  );
}

export default About;
