import React from "react";
import {
  PageContainer,
  ContentContainer1,
  ContentContainer2,
  Title,
  SubContainer,
  Box,
  TextBody,
} from "./page_styles/about_style.js";
import Footer from "../components/footer/footer.js";

function About() {
  return (
    <>
      <PageContainer>
        <section>
          <div class="air air1"></div>
          <div class="air air2"></div>
          <div class="air air3"></div>
          <div class="air air4"></div>
        </section>
        <ContentContainer1>
          <Title>Building Tomorrow's Maritime Frontier</Title>
        </ContentContainer1>
        <ContentContainer2>
          <SubContainer>
            <Box>Vision</Box>
            <TextBody>
              We’re focused on scaling access to mission-critical maritime data.
              As a team of watch officers, veterans, and software engineers, our
              experience illuminated the challenges of the maritime environment
              and the need to operate with data-driven insights - at the ship
              and watch floor level.
            </TextBody>
          </SubContainer>
          <SubContainer>
            <Box>Approach</Box>
            <TextBody>
              <p>
                Today’s enterprise software overlooks vast amounts of data
                generated by ships across the sea. Watch officers, with
                significant responsibility in their hands, are left to make
                high-stakes judgment calls without software that serves them the
                most relevant information.
              </p>
              <p>
                Marview is building an answer: our platform fuses open-source
                data and interfaces with existing sensors throughout the
                maritime network, offering key, actionable insights on a single
                screen.
              </p>
              <p>
                We’re committed to the opportunities presented by an explosion
                in satellite bandwidth, open-source data streams, and maritime
                sensor capabilities. The maritime domain is too important, and
                too challenging, to rely on analog methods any longer.
              </p>
            </TextBody>
          </SubContainer>
        </ContentContainer2>
      </PageContainer>
      <Footer />
    </>
  );
}

export default About;
